### ISSUE TITLE
Please add x64 version plugin

### ISSUE THREAD

**Issue by alexey-gorshkov** [ffes/indentbyfold#10]
Hi, this version not working win10 x64 notepad++

**Comment by lacan** [comment]
Seconded!

**Comment by divinity76** [comment]
in what situation do you actually need the 64bit version of notepad++?

i could understand it if it was about opening +4GB files, but the 64bit notepad++ version won't even do that

**Comment by ffes** [comment]
For now, you can download it here:
https://www.dropbox.com/s/nu6dn7wsoyjcj6h/IndentByFold-2017-09-19-x64.zip?dl=0

**Comment by lacan** [comment]
> `in what situation do you actually need the 64bit version of notepad++?`

While I understand your comment about its use, fact is Notepad++ has a 64-bit version. And it simply adds to the visibility of this plugin to offer it in 32bit and 64bit versions, despite a lack of real usefulness. 
> `For now, you can download it here:`

Thank you so much!

**Comment by hyagli** [comment]
> in what situation do you actually need the 64bit version of notepad++?
> 
> i could understand it if it was about opening +4GB files, but the 64bit notepad++ version won't even do that

I install notepad++ using chocolatey and it automatically installs the 64bit version.

**Comment by LUCScape** [comment]
Enterprises are switching everything and Microsoft Office to 64-bit (although it's not visible yet, the work is happening).  We do Notepad++ 64-bit with plugins.

**Comment by ffes** [comment]
I just released v0.7.2 which is basically the release of the 64-bit version of the plugin

I will create a PR for the builtin plugin manager of Notepad++ later this day. How long that takes to be included in the release of Notepad++ is out of my control
