### ISSUE TITLE
If Then Else in C gets indented wrong

### ISSUE THREAD

**Issue by abouatef** [ffes/indentbyfold#12]
```
void UART_puts(char *Output, unsigned int length)
{
	uint8_t i;
	for(int i=0;i<length;i++)
		Output[i] = UART_putc();
}
```

gets turned into

```
void UART_puts(char *Output, unsigned int length)
{
	uint8_t i;
	for(int i=0;i<length;i++)
	Output[i] = UART_putc();
}
```

Basically the same as issue #1 , but for C. whenever there is no curly braces around a piece of code it gets parsed as the top-level indentation, all that's needed is just some exceptions for the flow-control statements.

**Comment by ffes** [comment]
I recently added a FAQ about this problem:  
https://indentbyfold.readthedocs.io/en/latest/faq.html#faq-if-else

I am closing this issue as a dup of #1
