### ISSUE TITLE
Please provide keyboard shortcut

### ISSUE THREAD

**Issue by FilippoPagano** [ffes/indentbyfold#13]
Hello, 

thank you for the good plugin!

Can someone implement a keyboard shortcut?
I think everybody would highly appreciate.

Thank you again.

Regards,
Filippo

**Comment by ffes** [comment]
You can do that yourself in the settings

**Comment by root-ansh** [comment]
if someone is still wondering, the shortcuts settings could be found in `Settings>Shortcut mapper` (npp v7.8.9, indentbyfold v0.7.4)
![image](https://user-images.githubusercontent.com/31290636/92312742-69cdda80-efe1-11ea-858b-acd72dbc5b67.png)
